"""Replacement for the E21 exact-list tripwire (board D42, 2026-10-03).

The old test asserted that exactly two corpus rows (aiid_id 1574 and 1575)
carried an AIID signal over a non-AIID description. That pinned a population
which grew 2 -> 42 in two weeks (docs/audits/refresh-tripwire-2026-10-03.md),
so the weekly refresh could only be cleared by editing the test, and the
check had three named blind spots:

  1. a description that merely STARTS with ``AI Incident Database (AIID)
     entry #n: `` passed (prefix regex);
  2. rows outside the two ingest files it built from (``aiid_id`` 898 /
     INC-08183 came in through other files);
  3. the ``title`` field was never looked at.

Design here: every corpus row carrying an ``aiid_id`` must be EXPLAINED by an
independent derivation, never by a pattern.

  A. AIID-authored: ``description`` is byte-equal to the description of an
     ``ingest/aiid_full.json`` row whose source_id is one of the row's
     source_ids, and the row does not claim OECD provenance.
  B. OECD-template: ``description`` is byte-equal to
     ``ingest_oecd_aim.build_description()`` re-run on the fields of an
     ``OECD-AIM-*`` raw row among the row's source_ids, AND the row is
     labelled ``description_provenance == "original"`` /
     ``description_source == "oecd-aim"`` (WS4-T12).
  C. Anything else fails, except the explicitly dated exemptions below, and
     an exemption that is no longer needed fails too (a stale exemption is a
     silent hole).

Titles of explained rows must equal the title of one of the row's raw member
source rows.

Fail-closed: a new OECD->AIID row that ships unexplained text, or an
unlabelled OECD template, fails the weekly job's `Unit tests` step and no
refresh PR opens, exactly as the old tripwire did, but without a count to
edit. The merge side (new merges / retitles of published IDs) is gated at
build time by ``merge_and_dedupe._check_refresh_merge_authorization``
(tests/test_d42_refresh_merge_gate.py).

Scope limit, stated: built in-process from ``ingest/*.json`` only. The
gitignored ``data/legacy_consolidated.json`` (regenerated by
parse_existing.py) is not read, so legacy-only rows are out of scope.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

import pytest

import ingest_oecd_aim as oecd
import merge_and_dedupe as m

ROOT = Path(__file__).resolve().parents[1]
INGEST = ROOT / "ingest"

# aiid_id -> why it is allowed to be unexplained today. Dated; must be
# removed (and the test will force it) once the row is fixed.
KNOWN_UNEXPLAINED = {
    898: (
        "INC-08183, 2026-10-03 (docs/audits/E21-tripwire-refresh-2026-09-14.md "
        "'blind spot'): research-blog text under an AIID-898 cross-reference; "
        "fix is a curation override (data/ edit), owed to a separate task."
    ),
}


def _raw_index() -> tuple[dict[str, dict], list[dict]]:
    by_sid: dict[str, dict] = {}
    all_raw: list[dict] = []
    for src in sorted(INGEST.glob("*.json")):
        for r in m.load_source(src):
            all_raw.append(r)
            sid = r.get("source_id")
            if sid:
                by_sid.setdefault(sid, r)
    return by_sid, all_raw


def _aiid_descriptions() -> dict[str, str]:
    out = {}
    for r in m.load_source(INGEST / "aiid_full.json"):
        if r.get("source_id"):
            out[r["source_id"]] = r.get("description", "")
    return out


def explain_aiid_signal_rows(
    surviving: list[dict],
    raw_by_sid: dict[str, dict],
    aiid_desc: dict[str, str],
    exemptions: dict[int, str] = KNOWN_UNEXPLAINED,
) -> list[str]:
    """Return a list of problems (empty == every aiid_id row is explained)."""
    problems: list[str] = []
    unexplained: set[int] = set()
    for e in surviving:
        aid = e.get("aiid_id")
        if not aid:
            continue
        sids = e.get("source_ids") or []
        desc = e.get("description", "")
        prov = (e.get("description_provenance"), e.get("description_source"))

        # normalize_entry collapses runs of whitespace (the snapshot template
        # has a few double spaces from upstream titles); nothing else may differ.
        a_ok = any(
            desc and " ".join(aiid_desc.get(s, "").split()) == " ".join(desc.split())
            for s in sids
            if s.startswith("AIID-")
        )
        b_ok = False
        for s in sids:
            if not s.startswith("OECD-AIM-"):
                continue
            r = raw_by_sid.get(s)
            if not r:
                continue
            url = f"https://oecd.ai/en/incidents/{s[len('OECD-AIM-'):]}"
            if oecd.build_description(
                s, r.get("date", ""), url, r.get("affected", ""), r.get("attack_vector", "")
            ) == desc:
                b_ok = True
                break

        if a_ok:
            if prov[1] == "oecd-aim":
                problems.append(
                    f"aiid_id {aid} ({e.get('id')}): ships AIID-authored text but is labelled "
                    "oecd-aim (an override or backfill landed on the wrong anchor)"
                )
        elif b_ok:
            if prov != ("original", "oecd-aim"):
                problems.append(
                    f"aiid_id {aid} ({e.get('id')}): OECD template under an AIID signal is "
                    f"unlabelled (provenance={prov})"
                )
        else:
            unexplained.add(int(aid))
            if int(aid) not in exemptions:
                problems.append(
                    f"aiid_id {aid} ({e.get('id')}): description matches neither an AIID "
                    f"snapshot row nor build_description() of an OECD row: {desc[:80]!r}"
                )

        if a_ok or b_ok:
            titles = {
                " ".join((raw_by_sid[s].get("title") or "").split())
                for s in sids
                if s in raw_by_sid
            }
            if " ".join((e.get("title") or "").split()) not in titles:
                problems.append(
                    f"aiid_id {aid} ({e.get('id')}): title {e.get('title')!r} is not the title "
                    "of any raw member source row"
                )

    for aid in exemptions:
        if aid not in unexplained:
            problems.append(
                f"exemption for aiid_id {aid} is stale (row is now explained or gone): "
                "remove it from KNOWN_UNEXPLAINED"
            )
    return problems


def _build_surviving() -> list[dict]:
    raw_by_sid, all_raw = _raw_index()
    normalized = [n for n in (m.normalize_entry(dict(r)) for r in all_raw) if n is not None]
    surviving, _ = m.dedupe_entries(normalized)
    # Step 4d of the real pipeline: curation overrides keyed by any member.
    m.apply_curation_overrides(surviving, m._load_curation_overrides())
    return surviving


@pytest.fixture(scope="module")
def built():
    raw_by_sid, _ = _raw_index()
    return _build_surviving(), raw_by_sid, _aiid_descriptions()


def test_every_aiid_signal_row_is_explained(built):
    surviving, raw_by_sid, aiid_desc = built
    aiid_rows = [e for e in surviving if e.get("aiid_id")]
    # Positive control: the population checked must be the real one, or a
    # broken loader would pass this vacuously.
    assert len(aiid_rows) > 1000, f"only {len(aiid_rows)} aiid_id rows; loader broken?"
    assert any(e["aiid_id"] == 898 for e in aiid_rows), "898 must be in scope (old blind spot)"
    problems = explain_aiid_signal_rows(surviving, raw_by_sid, aiid_desc)
    assert not problems, "\n".join(problems[:30]) + (
        f"\n... {len(problems)} total" if len(problems) > 30 else ""
    )


# ---- prove the check can fire: each mutation is the named blind spot -------


def _first_row(built, pred):
    surviving, raw_by_sid, aiid_desc = built
    return copy.deepcopy(next(e for e in surviving if pred(e)))


def _is_oecd_b(e):
    return (
        e.get("aiid_id")
        and e.get("description", "").startswith("Tracked by the OECD AI Incidents")
        and e.get("description_source") == "oecd-aim"
    )


def _is_aiid_a(e):
    return e.get("aiid_id") and e.get("description", "").startswith("AI Incident Database (AIID)")


def _run(built, rows):
    _, raw_by_sid, aiid_desc = built
    return explain_aiid_signal_rows(rows, raw_by_sid, aiid_desc, exemptions={})


def test_control_unmutated_rows_are_explained(built):
    b = _first_row(built, _is_oecd_b)
    a = _first_row(built, _is_aiid_a)
    assert _run(built, [a, b]) == []


def test_fires_on_aiid_prefix_spoof(built):
    """Blind spot 1: OECD-authored prose that starts with the AIID prefix."""
    a = _first_row(built, _is_aiid_a)
    a["description"] = "AI Incident Database (AIID) entry #1: narrative prose that AIID never wrote."
    assert any("matches neither" in p for p in _run(built, [a]))


def test_fires_on_unlabelled_oecd_template(built):
    """The 40-row class: OECD template under an AIID signal with no label."""
    b = _first_row(built, _is_oecd_b)
    b["description_provenance"] = None
    b["description_source"] = None
    assert any("unlabelled" in p for p in _run(built, [b]))


def test_fires_on_oecd_label_on_aiid_text(built):
    """The step-4d hazard: an override keyed by a non-anchor member."""
    a = _first_row(built, _is_aiid_a)
    a["description_provenance"], a["description_source"] = "original", "oecd-aim"
    assert any("wrong anchor" in p for p in _run(built, [a]))


def test_fires_on_title_not_from_any_member(built):
    """Blind spot 3: the title field."""
    b = _first_row(built, _is_oecd_b)
    b["title"] = "A headline no member source row carries"
    assert any("title" in p for p in _run(built, [b]))


def test_fires_on_prose_stuffed_into_entities_slot(built):
    """The 09-14 regex accepted any prose before a period in the 'Entities
    named' slot; exact reconstruction does not."""
    b = _first_row(built, _is_oecd_b)
    d = b["description"]
    assert " See the AIM incident page" in d
    b["description"] = d.replace(
        " See the AIM incident page",
        " Entities named in the record: a whole narrative paragraph.  See the AIM incident page",
        1,
    )
    assert any("matches neither" in p for p in _run(built, [b]))


def test_fires_on_stale_exemption(built):
    surviving, raw_by_sid, aiid_desc = built
    probs = explain_aiid_signal_rows(surviving, raw_by_sid, aiid_desc, exemptions={999999: "x"})
    assert any("stale" in p and "999999" in p for p in probs)


def test_fires_on_row_outside_the_old_two_file_scope(built):
    """Blind spot 2: 898 must be caught when its exemption is removed."""
    surviving, raw_by_sid, aiid_desc = built
    probs = explain_aiid_signal_rows(surviving, raw_by_sid, aiid_desc, exemptions={})
    assert any("aiid_id 898" in p for p in probs)
